services:
  keycloak-service:
    container_name: keycloak-service
    image: quay.io/keycloak/keycloak:26.1.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    ports:
      - "8090:8080"
    networks:
      - back
    restart: unless-stopped
  
#  exchange-service:
#    build:
#      context: ./exchange
#      dockerfile: Dockerfile
#    ports:
#      - "${SERVER_PORT}:${SERVER_PORT}"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://${EXCHANGE_DB_HOST}:5432/${EXCHANGE_DB_NAME}
#      SPRING_DATASOURCE_USERNAME: ${EXCHANGE_DB_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${EXCHANGE_DB_PASSWORD}
#      SERVER_PORT: ${SERVER_PORT}
#    depends_on:
#      - exchange-db
#      - keycloak-service
#    networks:
#      - back

  exchange-db:
    image: postgres:16
    container_name: exchange-db
    environment:
      POSTGRES_DB: ${EXCHANGE_DB_NAME} # имя базы, которая создаётся при старте контейнера
      POSTGRES_USER: ${EXCHANGE_DB_USERNAME}
      POSTGRES_PASSWORD: ${EXCHANGE_DB_PASSWORD}
    ports:
      - "5435:5432"
    networks:
      - back

networks:
  back:
    driver: bridge