spring:
  application:
    name: order-application
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${SERVER_PORT:8082}

user-client:
  base-url: ${USER_CLIENT_BASE_URL}

application:
  nats:
    url: nats://localhost:4222
  outbox:
    order:
      topic-name: "orders.create"
      limit: 5

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

